"""has_avatar

Revision ID: 68851bcc09f9
Revises: ad7578819a15
Create Date: 2019-10-18 20:29:18.211410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68851bcc09f9'
down_revision = 'ad7578819a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_avatar', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_avatar')
    # ### end Alembic commands ###
