"""user email

Revision ID: cea0d12853da
Revises: b4ca15ccfd41
Create Date: 2019-09-07 19:40:11.678854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_searchable import sync_trigger


# revision identifiers, used by Alembic.
revision = 'cea0d12853da'
down_revision = 'b4ca15ccfd41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.UnicodeText(), nullable=True))

    conn = op.get_bind()
    sync_trigger(conn, 'post', 'search_vector', ['title', 'summary', 'markdown_body'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')

    conn = op.get_bind()
    sync_trigger(conn, 'post', 'search_vector', ['title', 'summary', 'markdown_body'])
    # ### end Alembic commands ###
